### ISSUE TITLE
Some points for improvement in use

### ISSUE THREAD

**Issue by jacques-tony** [opentibiabr/remeres-map-editor#51]
Estou deixando comentado aqui para não se perder em nossa conversa, fora os pontos apontados abaixo estou usando essa pr e tem funcionado bem._ 

**- Show indicators for pickupable and moveable items**

Testado e funcionando normalmente, seria interessante se tivesse um atalho para o uso ele fica no final da lista dentro de um menu lateral.

**- Fix: drawing always refreshing ui**

Testado e funcionando normalmente

**- Option to remove empty spawns and Add undo/redo after remove empty spawns**

Testado e funcionando normalmente o spawn de NPC não tem nenhum indicativo, antes tinha um fogo laranjinha

![image](https://github.com/opentibiabr/remeres-map-editor/assets/124947685/84fd8735-c9ca-4588-90fb-a308cd8ee527)

**- Draws position indicator**

Testado e funcionando normalmente

**- Avoid adding a new Unique ID if it already exists**
Testado e funcionando, mas se você copiar um objeto que já tenha um unique ID ele, ele vai duplicar o unique ID

**- Elementos na paleta Doodad não esta sendo possível selecionar eles com o click direito no mapa.** 
Agora
![image (1)](https://github.com/opentibiabr/remeres-map-editor/assets/124947685/ce9bd0d4-ef24-432c-8255-d2e13e2be5b1)
Antes
![image (2)](https://github.com/opentibiabr/remeres-map-editor/assets/124947685/d54bb20e-8259-43f0-b2a3-1cc48ca917a9)

**- Grid do comando SHIFT + I não esta ficando centralizado na tela, conforme o zoom vai aumentando ele vai se deslocando.** 

![image (3)](https://github.com/opentibiabr/remeres-map-editor/assets/124947685/973abbcc-55fa-41f8-8e6c-7c000069f3c8)
![image (4)](https://github.com/opentibiabr/remeres-map-editor/assets/124947685/5f11f744-718b-4455-ae2e-c19231b17ceb)

**- Teleport copy/paste improvements**
Quando se define nas configurações o terceiro tipo de "Copy Position Format - x,y,z ele não cola separado nos itens que tem o campo destination 
![image (5)](https://github.com/opentibiabr/remeres-map-editor/assets/124947685/789c12ab-b624-4078-836a-c621ed827c2f)
![image (6)](https://github.com/opentibiabr/remeres-map-editor/assets/124947685/430fdcca-ba55-453b-b24b-58ccf0478213)
![GIF 07-07-2023 09-55-41](https://github.com/opentibiabr/remeres-map-editor/assets/124947685/ec9363d2-3f5c-4fea-ad10-98a2384b3e8d)

**-Add function to get minimap/8bit color**
Testado e funcionando normalmente

**-Fix flood fill**
Testado e funcionando normalmente

**- Brush preview as vezes desaparece.** 
![brush preview](https://github.com/opentibiabr/remeres-map-editor/assets/124947685/0a1220e2-d670-4a37-82ca-898f99bc9dfe)

**- Ao criar uma nova paleta em "Window > New Palette" e usá-la como a Paleta de Waypoints, ela não funciona conforme o esperado.**

https://github.com/opentibiabr/remeres-map-editor/assets/124947685/6c448880-73cf-4872-85e7-13cc62ac6ddf

_Originally posted by @jacques-tony in https://github.com/opentibiabr/remeres-map-editor/issues/36#issuecomment-1625400430_

**Comment by phacUFPE** [comment]
Commenting only about the bugs that were found, the ones that was working I skipped.

- Elementos na paleta Doodad não esta sendo possível selecionar eles com o click direito no mapa.
Working as expected, tested on August 12, 2024.

- Brush preview as vezes desaparece.
Not able to reproduce, lack of information. I tested and the behavior that you reported didn't happened with me.

- Ao criar uma nova paleta em "Window > New Palette" e usá-la como a Paleta de Waypoints, ela não funciona conforme o esperado.
Confirmed, I'll be investigating.

- Teleport copy/paste improvements
Confirmed, only the third option, pattern "x, y, z" is not pasting correctly, I'll be investigating.

- Grid do comando SHIFT + I não esta ficando centralizado na tela, conforme o zoom vai aumentando ele vai se deslocando.
Not able to confirm, because this could be confused with the behavior of the zoom, the map zoom out in the opposite side that the mouse pointer is, and it zoom in to the mouse pointer. I don't know if the map can be zoom in/out with 100% of accuracy avoid the map to shift the location, it need further testing.
